server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/corona #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #띄어쓰기 6칸
    properties:
      hibernate:
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
  config:
    activate:
      on-profile: default

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace